// saving temporary scripting define symbol

public static class CUSTOM_DEFINE_SYMBOLS {
    public const string CUSTOM_SYMBOL_ENABLE_FACEBOOK = "CUSTOM_SYMBOL_ENABLE_FACEBOOK";
    public const string CUSTOM_SYMBOL_ENABLE_FIREBASE = "CUSTOM_SYMBOL_ENABLE_FIREBASE";
	
    public const string CUSTOM_SYMBOL_ENABLE_ADMOB = "CUSTOM_SYMBOL_ENABLE_ADMOB";
    public const string CUSTOM_SYMBOL_ENABLE_IRONSOURCE = "CUSTOM_SYMBOL_ENABLE_IRONSOURCE";
    public const string CUSTOM_SYMBOL_ENABLE_APPLOVIN = "CUSTOM_SYMBOL_ENABLE_APPLOVIN";
    public const string CUSTOM_SYMBOL_ENABLE_UNITYADS = "CUSTOM_SYMBOL_ENABLE_UNITYADS";
    public const string CUSTOM_SYMBOL_ENABLE_FBADS = "CUSTOM_SYMBOL_ENABLE_FBADS";
	
    public const string CUSTOM_SYMBOL_ENABLE_SIMPLE_ANDROID_NOTIFICATION = "CUSTOM_SYMBOL_ENABLE_SIMPLE_ANDROID_NOTIFICATION";

}